problem:
  class: hr.fer.zemris.edaf.testing.problems.MaxOnes
  genotype:
    type: binary
    length: 20

algorithm:
  name: mimic
  population:
    size: 100
  selection:
    name: tournament
    size: 50
  termination:
    max-generations: 200
