problem:
  class: com.knezevic.edaf.testing.problems.Ackley
  genotype:
    type: fp
    length: 10
    l-bound: -5.0
    u-bound: 5.0

algorithm:
  name: umda
  population:
    size: 300
  selection:
    name: tournament
    size: 3
  termination:
    max-generations: 2000

