problem:
  class: com.knezevic.edaf.testing.problems.TSP
  parameters:
    n: 30
    seed: 42
  genotype:
    type: permutation
    length: 30
    crossing:
      name: pmx
    mutation:
      name: swap
      probability: 0.1

algorithm:
  name: gga
  population:
    size: 200
  selection:
    name: tournament
    size: 3
  termination:
    max-generations: 1000
  elitism: 2

