problem:
  class: com.knezevic.edaf.testing.problems.crypto.BooleanFunctionProblem
  optimization: max
  parameters:
    n: 6
    criteria:
      - nonlinearity
  genotype:
    type: binary
    length: 64

algorithm:
  name: bmda
  population:
    size: 300
  selection:
    name: tournament
    size: 3
  termination:
    max-generations: 1000

