problem:
  class: com.knezevic.edaf.testing.bbob.BBOBProblem
  parameters:
    benchmarkId: 1
    instanceId: 1
    dimension: 10
  genotype:
    type: fp
    length: 10
    l-bound: -5.0
    u-bound: 5.0

algorithm:
  name: boa
  termination:
    max-generations: 200
  parameters:
    n_init: 20
    n_iter: 200
  log-frequency: 10
  log-directory: "logs/boa-sphere"

