problem:
  class: com.knezevic.edaf.testing.problems.misc.RastriginProblem
  optimization: min
  genotype:
    type: fp
    length: 10
    lowerBound: -5.12
    upperBound: 5.12

algorithm:
  name: boa
  population:
    size: 50
  termination:
    max-generations: 200

