problem:
  class: com.knezevic.edaf.testing.problems.Rosenbrock
  optimization: min
  genotype:
    type: fp
    length: 10
    l-bound: -5.0
    u-bound: 5.0

algorithm:
  name: boa
  population:
    size: 50
  termination:
    max-generations: 200

