problem:
  class: com.knezevic.edaf.testing.problems.Knapsack01
  optimization: max
  parameters:
    items: 30
    capacity: 80
    seed: 42
  genotype:
    type: binary
    length: 30

algorithm:
  name: bmda
  population:
    size: 50
  selection:
    name: tournament
    size: 3
  termination:
    max-generations: 200

