# Configuration for optimizing a boolean function using a permutation encoding.
# The goal is to evolve a balanced boolean function of 4 variables with high nonlinearity.

algorithm:
    name: ega
    elitism: 2
    population:
        size: 200
    selection:
        name: tournament
        size: 5
    termination:
        max-generations: 500

problem:
    class: com.knezevic.edaf.testing.problems.crypto.BooleanFunctionPermutationProblem
    params:
        n: 4
        criteria:
            - nonlinearity
    genotype:
        type: permutation
        length: 16 # 2^n
        crossing:
            name: pmx # Partially-Mapped Crossover is a good choice for this type of problem
            probability: 0.8
        mutation:
            name: swap
            probability: 0.2
