# Configuration for optimizing a boolean function for both balancedness and nonlinearity.

algorithm:
    name: ega
    elitism: 1
    population:
        size: 200
    selection:
        name: tournament
        size: 5
    termination:
        max-generations: 1000

problem:
    class: com.knezevic.edaf.examples.crypto.BooleanFunctionProblem
    params:
        n: 8
        criteria:
            - balancedness
            - nonlinearity
    genotype:
        type: binary
        length: 256 # 2^n
        crossing:
            name: one-point
            probability: 0.8
        mutation:
            name: simple
            probability: 0.01
