problem:
  class: com.knezevic.edaf.testing.problems.Ackley
  optimization: min
  genotype:
    type: fp
    length: 10
    l-bound: -32.768
    u-bound: 32.768

algorithm:
  name: cem
  population:
    size: 100
  selection:
    name: tournament
    size: 3
  termination:
    max-generations: 200
  parameters:
    batchSize: 100
    eliteFraction: 0.1
    learningRate: 0.7

