problem:
  class: com.knezevic.edaf.testing.problems.Rosenbrock
  optimization: min
  genotype:
    type: fp
    length: 10
    lowerBound: -5.0
    upperBound: 5.0

algorithm:
  name: cem
  population:
    size: 100
  selection:
    name: tournament
    size: 10
  termination:
    max-generations: 200
  parameters:
    batchSize: 100
    eliteFraction: 0.1
    learningRate: 0.7

