problem:
  class: com.knezevic.edaf.testing.problems.MaxOnes
  optimization: max
  genotype:
    type: binary
    length: 100

algorithm:
  name: cem
  population:
    size: 100
  selection:
    name: tournament
    size: 10
  termination:
    max-generations: 100
  parameters:
    batchSize: 100
    eliteFraction: 0.1
    learningRate: 0.7

