problem:
  class: com.knezevic.edaf.testing.problems.Knapsack01
  optimization: max
  parameters:
    items: 50
    capacity: 120
    seed: 42
  genotype:
    type: binary
    length: 50

algorithm:
  name: cem
  population:
    size: 100
  selection:
    name: tournament
    size: 3
  termination:
    max-generations: 500
  parameters:
    batchSize: 100
    eliteFraction: 0.1
    learningRate: 0.7

