problem:
  class: com.knezevic.edaf.testing.problems.MaxOnes
  genotype:
    type: binary
    length: 20

algorithm:
  name: cga
  termination:
    max-generations: 10000
  log-frequency: 10
  log-directory: "logs/cga-max-ones"
  parameters:
    n: 10
