# Parity problem for CGP - classic GP benchmark
# Task: Create a function that outputs 1 if odd number of inputs are 1, else 0

problem:
  class: com.knezevic.edaf.algorithm.cgp.problems.CgpParityProblem
  optimization: min
  genotype:
    type: integer
    length: 100

algorithm:
  name: cgp
  population:
    size: 200
  selection:
    name: tournament
    size: 3
  termination:
    max-generations: 500
  parameters:
    populationSize: 200
    mutationRate: 0.03
    rows: 1
    cols: 25
    levelsBack: 10
    useCrossover: false
    replacementStrategy: GENERATIONAL

