problem:
  class: com.knezevic.edaf.algorithm.cgp.problems.CgpBooleanFunctionProblem
  optimization: max
  genotype:
    type: integer
    length: 100

algorithm:
  name: cgp
  population:
    size: 200
  selection:
    name: tournament
    size: 3
  termination:
    max-generations: 500
  parameters:
    populationSize: 200
    mutationRate: 0.03
    rows: 1
    cols: 25
    levelsBack: 10
    useCrossover: false
    replacementStrategy: GENERATIONAL

