# Configuration for the Deceptive Trap Function problem.
# This problem is designed to be difficult for simple hill-climbers and tests
# an algorithm's ability to identify and combine "building blocks" of a solution.

algorithm:
    # The Compact Genetic Algorithm (cGA) is a good choice for this problem
    # as it explicitly models the distribution of good bits.
    name: cga
    # The 'n' parameter for cGA represents the virtual population size used for updates.
    parameters:
        n: 100
    termination:
        max-generations: 300

problem:
    class: com.knezevic.edaf.examples.misc.DeceptiveTrapProblem
    genotype:
        # This is a binary problem.
        type: binary
        # The length must be a multiple of k (which is 4 in the problem class).
        length: 40
