problem:
  class: com.knezevic.edaf.testing.problems.MaxOnes # Note: This is not an integer problem, just for demonstration
  genotype:
    type: integer
    length: 20
    min-bound: 0
    max-bound: 100
    crossing:
      name: one-point
    mutation:
      name: simple
      probability: 0.05

algorithm:
  name: gga
  population:
    size: 100
  selection:
    name: tournament
    size: 3
  termination:
    max-generations: 100
  elitism: 1
  log-frequency: 10
  log-directory: "logs/ga-integer-example"
