problem:
  class: com.knezevic.edaf.testing.problems.MaxOnes
  genotype:
    type: binary
    length: 20
    crossing:
      name: one-point
      probability: 0.2
    mutation:
      name: simple
      probability: 0.1

algorithm:
  name: gga
  population:
    size: 100
  selection:
    name: mu-plus-lambda
    mu: 10
    lambda: 50
  termination:
    max-generations: 1000
  elitism: 1
  log-frequency: 10
  log-directory: "logs/gga-mu-plus-lambda"
