problem:
  class: com.knezevic.edaf.testing.problems.Knapsack01
  optimization: max
  parameters:
    items: 50
    capacity: 120
    seed: 42
  genotype:
    type: binary
    length: 50

algorithm:
  name: ltga
  population:
    size: 200
  termination:
    max-generations: 500

