problem:
  class: com.knezevic.edaf.testing.problems.Sphere
  optimization: min
  genotype:
    type: fp
    length: 10
    l-bound: -5.0
    u-bound: 5.0
    mutation:
      name: polynomial
      probability: 0.1
      distribution-index: 20.0

algorithm:
  name: umda
  population:
    size: 200
  selection:
    name: tournament
    size: 3
  termination:
    max-generations: 500

