problem:
  class: com.knezevic.edaf.testing.problems.misc.DeceptiveTrapProblem
  optimization: max
  k: 5
  genotype:
    type: binary
    length: 40
    mutation:
      name: simple
      probability: 0.01

algorithm:
  name: ltga
  population:
    size: 200
  selection:
    name: tournament
    size: 3
  termination:
    max-generations: 500

