problem:
  class: com.knezevic.edaf.testing.problems.Sphere
  optimization: min
  genotype:
    type: fp
    length: 10
    lowerBound: -5.0
    upperBound: 5.0

algorithm:
  name: ltga
  population:
    size: 200
  termination:
    max-generations: 500

