problem:
  class: com.knezevic.edaf.testing.problems.misc.DeceptiveTrapProblem
  optimization: max
  parameters:
    k: 5
  genotype:
    type: binary
    length: 40

algorithm:
  name: mimic
  population:
    size: 200
  selection:
    name: tournament
    size: 3
  termination:
    max-generations: 500

