problem:
  class: com.knezevic.edaf.testing.problems.MaxOnes
  genotype:
    type: binary
    length: 20

algorithm:
  name: pbil
  population:
    size: 100
  selection:
    name: tournament
    size: 3
  termination:
    max-generations: 10000
  log-frequency: 10
  log-directory: "logs/pbil-max-ones"
  parameters:
    learning-rate: 0.1
    negative-learning-rate: 0.075
    mutation-prob: 0.02
    mutation-shift: 0.05
