problem:
  class: com.knezevic.edaf.testing.problems.Rosenbrock
  optimization: min
  genotype:
    type: fp
    length: 10
    l-bound: -5.0
    u-bound: 5.0

algorithm:
  name: pbil
  population:
    size: 200
  selection:
    name: tournament
    size: 3
  termination:
    max-generations: 500
  parameters:
    learning-rate: 0.1
    negative-learning-rate: 0.075
    mutation-prob: 0.02
    mutation-shift: 0.05

