problem:
  class: com.knezevic.edaf.testing.problems.misc.DeceptiveTrapProblem
  optimization: max
  parameters:
    k: 5
  genotype:
    type: binary
    length: 40

algorithm:
  name: pbil
  population:
    size: 200
  selection:
    name: tournament
    size: 50
  termination:
    max-generations: 500
  parameters:
    learning-rate: 0.1
    negative-learning-rate: 0.075
    mutation-prob: 0.02
    mutation-shift: 0.05

