# Configuration for optimizing the Rastrigin function using the UMDA algorithm.
# UMDA (Univariate Marginal Distribution Algorithm) is a type of EDA.

algorithm:
    name: umda
    # UMDA-specific parameters
    parameters:
        # Percentage of the population to be selected as the best individuals
        selection-ratio: 0.5
    population:
        size: 300
    selection:
        name: tournament
        size: 3
    termination:
        max-generations: 100000000

problem:
  class: com.knezevic.edaf.testing.problems.misc.RastriginProblem
  genotype:
    # RastriginProblem expects floating-point genotype (FpIndividual)
    type: fp
    length: 20 # 20-dimensional Rastrigin
    l-bound: -5.12
    u-bound: 5.12
