# Configuration for optimizing the Rastrigin function using the UMDA algorithm.
# UMDA (Univariate Marginal Distribution Algorithm) is a type of EDA.

algorithm:
    name: umda
    # UMDA-specific parameters
    parameters:
        # Percentage of the population to be selected as the best individuals
        selection-ratio: 0.5
    population:
        size: 300
    termination:
        max-generations: 1000

problem:
    class: com.knezevic.edaf.examples.misc.RastriginProblem
    genotype:
        # UMDA in this framework works with binary genotypes, so we need to encode the floats.
        type: binary
        length: 200 # 20 dimensions * 10 bits per dimension
        encoding: "gray" # Gray encoding is often better for numerical problems
        precision: 10
        l-bound: -5.12
        u-bound: 5.12
