problem:
  class: com.knezevic.edaf.testing.problems.MaxOnes
  genotype:
    type: binary
    length: 20

algorithm:
  name: umda
  population:
    size: 100
  selection:
    name: tournament
    size: 3
  termination:
    max-generations: 10000000
  log-frequency: 10
  log-directory: "logs/umda-max-ones"
  parameters:
    ratio: 0.5
