server:
  port: 7070

spring:
  datasource:
    url: ${EDAF_DB_URL:jdbc:sqlite:edaf-v3.db}
    username: ${EDAF_DB_USER:}
    password: ${EDAF_DB_PASS:}
  thymeleaf:
    cache: false

edaf:
  framework:
    version: ${EDAF_FRAMEWORK_VERSION:}
