problem:
  class: com.knezevic.edaf.algorithm.cgp.CgpBooleanFunctionProblem

algorithm:
  name: cgp
  parameters:
    populationSize: 100
    generations: 500
    mutationRate: 0.1
    functionSet: ["AND", "OR", "NOT", "XOR"]
    rows: 1
    cols: 20
    levelsBack: 10
    replacementStrategy: GENERATIONAL
    selection:
      name: tournament
      size: 5
  termination:
    max-generations: 500
  log-directory: "logs/cgp/boolean"
