# Configuration for a Genetic Programming experiment on the Iris classification problem.

algorithm:
    name: gp
    elitism: 2
    population:
        size: 150
    selection:
        name: tournament
        size: 3
    termination:
        max-generations: 75

problem:
    class: com.knezevic.edaf.testing.problems.gp.IrisClassificationProblem
    genotype:
        type: tree
        length: 1
        maxDepth: 5
        primitives:
            type: RealValued
            functionSet: ADD,SUB,MUL,DIV
            terminals:
                - { name: sepal_length, type: variable }
                - { name: sepal_width, type: variable }
                - { name: petal_length, type: variable }
                - { name: petal_width, type: variable }
        crossing:
            name: treeCrossover
            probability: 0.8
        mutation:
            name: treeMutation
            probability: 0.2
