package com.knezevic.edaf.reporting;

import com.knezevic.edaf.persistence.api.GenerationRecord;
import com.knezevic.edaf.persistence.api.RunMetadata;
import com.knezevic.edaf.persistence.api.RunResult;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Locale;

/**
 * Generates a Markdown report with tables and text summary.
 */
public class MarkdownReportGenerator implements ReportGenerator {

    private static final Logger log = LoggerFactory.getLogger(MarkdownReportGenerator.class);

    @Override
    public Path generate(RunMetadata metadata, RunResult result,
                         List<GenerationRecord> generations, Path outputDir) {
        try {
            Files.createDirectories(outputDir);
        } catch (IOException e) {
            log.error("Failed to create report directory: {}", outputDir, e);
            return null;
        }

        String md = buildMarkdown(metadata, result, generations);
        Path file = outputDir.resolve("report-" + metadata.runId() + ".md");
        try {
            Files.writeString(file, md);
            log.info("Markdown report written to {}", file);
            return file;
        } catch (IOException e) {
            log.error("Failed to write Markdown report to {}", file, e);
            return null;
        }
    }

    private String buildMarkdown(RunMetadata metadata, RunResult result,
                                  List<GenerationRecord> generations) {
        StringBuilder md = new StringBuilder();

        md.append("# EDAF Run Report\n\n");

        // Summary
        md.append("## Summary\n\n");
        md.append(String.format(Locale.US, "- **Algorithm:** %s%n", metadata.algorithmId()));
        md.append(String.format(Locale.US, "- **Best Fitness:** %.6f%n", result.bestFitness()));
        md.append(String.format("- **Generations:** %d%n", result.totalGenerations()));
        md.append(String.format("- **Duration:** %d ms%n%n", result.totalDurationMillis()));

        // Metadata
        md.append("## Run Metadata\n\n");
        md.append("| Property | Value |\n|---|---|\n");
        md.append(String.format("| Run ID | %s |%n", metadata.runId()));
        md.append(String.format("| Algorithm | %s |%n", metadata.algorithmId()));
        md.append(String.format("| Problem | %s |%n", metadata.problemClass()));
        md.append(String.format("| Genotype | %s |%n", metadata.genotypeType()));
        md.append(String.format("| Population Size | %d |%n", metadata.populationSize()));
        md.append(String.format("| Max Generations | %d |%n", metadata.maxGenerations()));
        if (metadata.seed() != null) {
            md.append(String.format("| Seed | %d |%n", metadata.seed()));
        }
        md.append(String.format("| Started | %s |%n", metadata.startedAt()));
        md.append(String.format("| Completed | %s |%n%n", result.completedAt()));

        // Generation table
        md.append("## Generation Statistics\n\n");
        md.append("| Gen | Best | Worst | Avg | Std |\n");
        md.append("|---:|---:|---:|---:|---:|\n");
        int step = Math.max(1, generations.size() / 30);
        for (int i = 0; i < generations.size(); i += step) {
            GenerationRecord g = generations.get(i);
            md.append(String.format(Locale.US, "| %d | %.6f | %.6f | %.6f | %.6f |%n",
                g.generation(), g.bestFitness(), g.worstFitness(), g.avgFitness(), g.stdFitness()));
        }
        if (step > 1 && !generations.isEmpty()) {
            GenerationRecord last = generations.get(generations.size() - 1);
            md.append(String.format(Locale.US, "| %d | %.6f | %.6f | %.6f | %.6f |%n",
                last.generation(), last.bestFitness(), last.worstFitness(), last.avgFitness(), last.stdFitness()));
        }

        md.append("\n---\n*Generated by EDAF Framework v2.0*\n");
        return md.toString();
    }
}
